// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1dtm53jur5mJDv6Y9em6FvM2ezAUNXs',
    appId: '1:523825357814:web:7640a60f31f5a5ff761dd7',
    messagingSenderId: '523825357814',
    projectId: 'calo-ai-f4722',
    authDomain: 'calo-ai-f4722.firebaseapp.com',
    storageBucket: 'calo-ai-f4722.firebasestorage.app',
    measurementId: 'G-8ZP7RMNKS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ED5H_rJQj-kdK1h45eBQ-9VgJH7ZED8',
    appId: '1:523825357814:android:baca3a080093f1dd761dd7',
    messagingSenderId: '523825357814',
    projectId: 'calo-ai-f4722',
    storageBucket: 'calo-ai-f4722.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9gd1sKzIPXpSJHu4Z37fhod2W1DtFX0k',
    appId: '1:523825357814:ios:4aaa1d0deb99e034761dd7',
    messagingSenderId: '523825357814',
    projectId: 'calo-ai-f4722',
    storageBucket: 'calo-ai-f4722.firebasestorage.app',
    iosClientId: '523825357814-2jhq4sppbtarkscjqrc4miq0t82hl2tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloAiAp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9gd1sKzIPXpSJHu4Z37fhod2W1DtFX0k',
    appId: '1:523825357814:ios:4aaa1d0deb99e034761dd7',
    messagingSenderId: '523825357814',
    projectId: 'calo-ai-f4722',
    storageBucket: 'calo-ai-f4722.firebasestorage.app',
    iosClientId: '523825357814-2jhq4sppbtarkscjqrc4miq0t82hl2tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloAiAp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm1dtm53jur5mJDv6Y9em6FvM2ezAUNXs',
    appId: '1:523825357814:web:3b09f60b6dc0c80e761dd7',
    messagingSenderId: '523825357814',
    projectId: 'calo-ai-f4722',
    authDomain: 'calo-ai-f4722.firebaseapp.com',
    storageBucket: 'calo-ai-f4722.firebasestorage.app',
    measurementId: 'G-G6FJ4M5H6F',
  );
}
